name: 自动同步上游 drpy-node
on:
  schedule:
    - cron: "0 2 * * *"  # 每天 UTC 2点（北京时间10点）自动同步
  workflow_dispatch:     # 允许手动触发同步

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 同步上游 main 分支
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: Neil-ZN/drpy-node
          upstream_sync_branch: main
